# Generated by Django 4.2.2 on 2024-02-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boppop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='contest',
            field=models.BooleanField(default=False),
        ),
    ]
