# Generated by Django 4.2.2 on 2024-02-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boppop', '0002_playlist_active_alter_playlist_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boppop.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
