# Generated by Django 4.2.2 on 2024-03-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boppop', '0003_playlist_number_playlist_winner_song_is_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
    ]
