[project]
name = "api"
version = "0.1.0"
description = "Bop Pop api sever"
authors = [
    {name = "Bop"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi (>=0.68.0,<0.69.0)",
    "pydantic (>=1.8.0,<2.0.0)",
    "uvicorn (>=0.15.0,<0.16.0)",
    "sqlalchemy (>=1.4.23,<1.5.0)",
    "psycopg2-binary (>=2.9.1,<3.0.0)",
    "python-jose[cryptography] (>=3.3.0,<4.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-multipart (>=0.0.5,<0.0.6)",
    "python-dotenv (>=0.19.0,<0.20.0)",
    "alembic (>=1.7.4,<1.8.0)",
    "strawberry-graphql[fastapi] (>=0.158.0)",
    "graphql-core (>=3.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
